### ISSUE TITLE
Add signed kernel check to prevent pushing improperly signed kernels

### ISSUE THREAD

**Issue by bsherman** [ublue-os/kernel-cache#16]
We shold add a step after image build and before push which confirms kernel in the image was signed with the proper key.

Can use: `podman run --entrypoint /bin/bash image -c "cat path to vmlinuz" > tmp/vmlinuz`

And then do a `sbverify --cert`

**Comment by m2Giles** [comment]
In downstream images this has been implemented.

But we can do something similar in this repo.

**Comment by m2Giles** [comment]
Implemented in #18
