### ISSUE TITLE
CoreOS Matched Kernel for F39

### ISSUE THREAD

**Issue by m2Giles** [ublue-os/kernel-cache#20]
Fedora changes the kernel version depending on where in the cycle a release is.

Right now, for F39, the matched coreos kernel is version 200. When the coreos kernel updates to 6.9.X, this will likely change to version 100.

We need to be able to dynamically determine which version is needed which we can do by probing for existence in koji.

**Comment by castrojo** [comment]
Aha, happened to catch it as it happened!

https://github.com/ublue-os/kernel-cache/actions/runs/10170848021/job/28130744854

Failed looking for `https://kojipkgs.fedoraproject.org//packages/kernel/6.9.7/200.fc39/x86_64/kernel-6.9.7-200.fc39.x86_64.rpm`

Which is missing, it's in 100.fc39 on the mirror.

**Comment by bsherman** [comment]
I've got some active development going on this issue.
