### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by mecattaf** [ublue-os/kernel-cache#8]
Hello and thank you for the very timely work here. 
The fsync kernel is the only way to solve a strange issue on my laptop, but I am not sure how to use this project with bluebuild. 
Can you confirm that this repo is meant to remplace akmods and that I can use it with the [akmods module](https://github.com/blue-build/modules/tree/main/modules/akmods)?
Best

**Comment by m2Giles** [comment]
This repo is for changing how we build akmods in the akmods repo and for installing different kernels for Bluefin and Bazzite. The akmods repo is not going away.

We are not currently signing the kernels here. Though we may do that in the future.
